"""
Read-only Prometheus exporter -- v0.10.0 ("Expose").

First step of the monitoring-integration arc ("The Translucency Control Plane",
PRESIDIO-REQ.md). ``pat export`` publishes the architectural-translucency model's
per-layer recommendations for a given workload as Prometheus metrics on a
read-only ``/metrics`` endpoint, so they can be scraped into Grafana alongside
the metrics teams already run -- closing the observe -> recommend -> visualize
loop without ``pat`` ever mutating infrastructure.

Arc invariant A1 ("pat emits, it never applies") and the v0.10.0 security notes:
  * Read-only. The server answers GET on ``/metrics`` (plus a ``/health``
    liveness probe) and nothing else -- there are no mutation endpoints.
  * Loopback by default. Binds 127.0.0.1 unless the caller explicitly opts into
    a routable interface with ``--listen-public``.
  * Metric names are fixed (never user input); label values are escaped.

The Prometheus exposition text is generated by hand (text format 0.0.4) to keep
the dependency surface minimal -- the same approach ``hpa_patch`` takes for YAML.
"""

from __future__ import annotations

import ipaddress
import math
from collections.abc import Callable
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, HTTPServer

from presidio_arch_translucency.model import ReplicationLayer, analyze

# Prometheus text exposition content type (format version 0.0.4).
CONTENT_TYPE_METRICS = "text/plain; version=0.0.4; charset=utf-8"
CONTENT_TYPE_TEXT = "text/plain; charset=utf-8"
METRICS_PATH = "/metrics"
HEALTH_PATHS = ("/health", "/healthz")
DEFAULT_PORT = 9847
LOOPBACK_HOST = "127.0.0.1"


@dataclass(frozen=True)
class Sample:
    """One metric sample: label set plus a value."""

    labels: dict[str, str]
    value: float


@dataclass(frozen=True)
class Metric:
    """A single named gauge with one or more samples."""

    name: str
    help: str
    samples: list[Sample]
    type: str = "gauge"


# -- exposition formatting (pure, fully testable without a socket) -------------


def _escape_help(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\n", "\\n")


def _escape_label_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_value(value: float) -> str:
    """Render a float in Prometheus-acceptable form (ints without trailing .0)."""
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "+Inf" if value > 0 else "-Inf"
    if float(value).is_integer():
        return str(int(value))
    return repr(float(value))


def render_exposition(metrics: list[Metric]) -> str:
    """Render *metrics* as a Prometheus text-format 0.0.4 document."""
    lines: list[str] = []
    for metric in metrics:
        lines.append(f"# HELP {metric.name} {_escape_help(metric.help)}")
        lines.append(f"# TYPE {metric.name} {metric.type}")
        for sample in metric.samples:
            if sample.labels:
                label_str = ",".join(
                    f'{key}="{_escape_label_value(val)}"'
                    for key, val in sample.labels.items()
                )
                series = f"{metric.name}{{{label_str}}}"
            else:
                series = metric.name
            lines.append(f"{series} {_format_value(sample.value)}")
    return "\n".join(lines) + "\n"


# -- metric construction -------------------------------------------------------


def _package_version() -> str:
    from presidio_arch_translucency import __version__  # noqa: PLC0415

    return __version__


def build_metrics(
    requests_per_second: float,
    avg_latency_ms: float,
    current_layer: ReplicationLayer,
    layer: str | None = None,
) -> list[Metric]:
    """
    Build the exporter's metric set from a single architectural-translucency
    analysis of the given workload.

    All metrics are gauges. Per-layer metrics carry a ``layer`` label
    (container/pod/deployment/node); the recommendation is marked by
    ``pat_layer_recommended``.
    """
    result = analyze(
        requests_per_second=requests_per_second,
        avg_latency_ms=avg_latency_ms,
        current_layer=current_layer,
        layer=layer,
    )

    replicas: list[Sample] = []
    throughput: list[Sample] = []
    response_time: list[Sample] = []
    gain_ratio: list[Sample] = []
    recommended: list[Sample] = []
    for lr in result.layers:
        labels = {"layer": lr.layer.value}
        replicas.append(Sample(labels, lr.optimal_replicas))
        throughput.append(Sample(labels, lr.estimated_throughput_rps))
        response_time.append(Sample(labels, lr.estimated_response_time_ms))
        gain_ratio.append(Sample(labels, lr.throughput_gain_pct / 100.0))
        recommended.append(
            Sample(labels, 1.0 if lr.layer == result.recommended_layer else 0.0)
        )

    return [
        Metric(
            "pat_build_info",
            "Build information for the running pat exporter (constant 1).",
            [Sample({"version": _package_version()}, 1.0)],
        ),
        Metric(
            "pat_workload_requests_per_second",
            "Configured workload demand in requests per second.",
            [Sample({}, requests_per_second)],
        ),
        Metric(
            "pat_workload_avg_latency_ms",
            "Configured workload average latency in milliseconds.",
            [Sample({}, avg_latency_ms)],
        ),
        Metric(
            "pat_recommended_replicas",
            "Recommended replica count to saturate demand at each layer.",
            replicas,
        ),
        Metric(
            "pat_estimated_throughput_rps",
            "Estimated throughput (req/s) at the recommended replica count per layer.",
            throughput,
        ),
        Metric(
            "pat_response_time_ms",
            "Estimated response time (ms) at the recommended replica count per layer.",
            response_time,
        ),
        Metric(
            "pat_throughput_gain_ratio",
            "Throughput gain over the single-replica baseline as a ratio "
            "(0.10 == +10%).",
            gain_ratio,
        ),
        Metric(
            "pat_layer_recommended",
            "1 for the cross-layer recommended layer, 0 otherwise.",
            recommended,
        ),
    ]


# -- HTTP serving --------------------------------------------------------------


def is_loopback_host(host: str) -> bool:
    """True when *host* is a loopback address (or the literal ``localhost``)."""
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def handle_request(path: str, provider: Callable[[], str]) -> tuple[int, str, bytes]:
    """
    Map a request path to ``(status, content_type, body)``.

    Pure and side-effect-free so it is testable without a socket. ``provider``
    is called only for the metrics path and returns the exposition text.
    """
    path = path.split("?", 1)[0]
    if path == METRICS_PATH:
        return 200, CONTENT_TYPE_METRICS, provider().encode("utf-8")
    if path in HEALTH_PATHS:
        return 200, CONTENT_TYPE_TEXT, b"ok\n"
    if path == "/":
        return 200, CONTENT_TYPE_TEXT, f"pat exporter -- GET {METRICS_PATH}\n".encode()
    return 404, CONTENT_TYPE_TEXT, b"not found\n"


def _make_handler(provider: Callable[[], str]) -> type[BaseHTTPRequestHandler]:
    class _MetricsHandler(BaseHTTPRequestHandler):
        # Only GET is implemented -> any other method gets 501 (read-only).
        def do_GET(self) -> None:  # noqa: N802
            status, content_type, body = handle_request(self.path, provider)
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *args: object) -> None:
            # Silence the default stderr access log.
            return

    return _MetricsHandler


def build_server(host: str, port: int, provider: Callable[[], str]) -> HTTPServer:
    """Create (but do not start) the read-only metrics HTTP server."""
    return HTTPServer((host, port), _make_handler(provider))
