"""
Read-only Prometheus exporter -- v0.10.0 ("Expose").

First step of the monitoring-integration arc ("The Translucency Control Plane",
PRESIDIO-REQ.md). ``pat export`` publishes the architectural-translucency model's
per-layer recommendations for a given workload as Prometheus metrics on a
read-only ``/metrics`` endpoint, so they can be scraped into Grafana alongside
the metrics teams already run -- closing the observe -> recommend -> visualize
loop without ``pat`` ever mutating infrastructure.

Arc invariant A1 ("pat emits, it never applies") and the v0.10.0 security notes:
  * Read-only. The server answers GET on ``/metrics`` (plus a ``/health``
    liveness probe) and nothing else -- there are no mutation endpoints.
  * Loopback by default. Binds 127.0.0.1 unless the caller explicitly opts into
    a routable interface with ``--listen-public``.
  * Metric names are fixed (never user input); label values are escaped.

The Prometheus exposition text is generated by hand (text format 0.0.4) to keep
the dependency surface minimal -- the same approach ``hpa_patch`` takes for YAML.
"""

from __future__ import annotations

import ipaddress
import math
from collections.abc import Callable
from dataclasses import dataclass
from http.server import BaseHTTPRequestHandler, HTTPServer

from presidio_arch_translucency.energy import (
    DEFAULT_REPLICA_POWER_WATTS,
    layer_energy,
)
from presidio_arch_translucency.model import (
    ReplicationLayer,
    analyze,
    base_capacity_rps,
    resolve_concurrency,
)

# Prometheus text exposition content type (format version 0.0.4).
CONTENT_TYPE_METRICS = "text/plain; version=0.0.4; charset=utf-8"
CONTENT_TYPE_TEXT = "text/plain; charset=utf-8"
METRICS_PATH = "/metrics"
HEALTH_PATHS = ("/health", "/healthz")
DEFAULT_PORT = 9847
LOOPBACK_HOST = "127.0.0.1"
DEFAULT_HORIZON_MINUTES = 10.0


@dataclass(frozen=True)
class Sample:
    """One metric sample: label set plus a value."""

    labels: dict[str, str]
    value: float


@dataclass(frozen=True)
class Metric:
    """A single named gauge with one or more samples."""

    name: str
    help: str
    samples: list[Sample]
    type: str = "gauge"


# -- exposition formatting (pure, fully testable without a socket) -------------


def _escape_help(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\n", "\\n")


def _escape_label_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_value(value: float) -> str:
    """Render a float in Prometheus-acceptable form (ints without trailing .0)."""
    if math.isnan(value):
        return "NaN"
    if math.isinf(value):
        return "+Inf" if value > 0 else "-Inf"
    if float(value).is_integer():
        return str(int(value))
    return repr(float(value))


def render_exposition(metrics: list[Metric]) -> str:
    """Render *metrics* as a Prometheus text-format 0.0.4 document."""
    lines: list[str] = []
    for metric in metrics:
        lines.append(f"# HELP {metric.name} {_escape_help(metric.help)}")
        lines.append(f"# TYPE {metric.name} {metric.type}")
        for sample in metric.samples:
            if sample.labels:
                label_str = ",".join(
                    f'{key}="{_escape_label_value(val)}"'
                    for key, val in sample.labels.items()
                )
                series = f"{metric.name}{{{label_str}}}"
            else:
                series = metric.name
            lines.append(f"{series} {_format_value(sample.value)}")
    return "\n".join(lines) + "\n"


# -- metric construction -------------------------------------------------------


def _package_version() -> str:
    from presidio_arch_translucency import __version__  # noqa: PLC0415

    return __version__


def build_metrics(
    requests_per_second: float,
    avg_latency_ms: float,
    current_layer: ReplicationLayer,
    layer: str | None = None,
    cost_per_replica_hour: float | None = None,
    replica_power_watts: float = DEFAULT_REPLICA_POWER_WATTS,
) -> list[Metric]:
    """
    Build the exporter's metric set from a single architectural-translucency
    analysis of the given workload.

    All metrics are gauges. Per-layer metrics carry a ``layer`` label
    (container/pod/deployment/node); the recommendation is marked by
    ``pat_layer_recommended``. When *cost_per_replica_hour* is given, per-layer
    cost gauges (``pat_cost_per_request``, ``pat_hourly_cost_usd``) are added
    using that uniform replica cost.

    Per-layer energy gauges (``pat_energy_per_request_joules``,
    ``pat_power_watts``, ``pat_energy_efficiency_index``) are always included —
    they are MODELLED outputs of the analytic energy model (v0.20.0), computed
    from the same analysis with :data:`DEFAULT_REPLICA_POWER_WATTS` exactly as
    ``pat analyze`` does. Their HELP text says so; a *measured* watt only ever
    reaches ``pat_measured_power_watts`` (see :func:`measured_energy_metrics`).
    """
    result = analyze(
        requests_per_second=requests_per_second,
        avg_latency_ms=avg_latency_ms,
        current_layer=current_layer,
        layer=layer,
    )

    replicas: list[Sample] = []
    throughput: list[Sample] = []
    response_time: list[Sample] = []
    gain_ratio: list[Sample] = []
    recommended: list[Sample] = []
    for lr in result.layers:
        labels = {"layer": lr.layer.value}
        replicas.append(Sample(labels, lr.optimal_replicas))
        throughput.append(Sample(labels, lr.estimated_throughput_rps))
        response_time.append(Sample(labels, lr.estimated_response_time_ms))
        gain_ratio.append(Sample(labels, lr.throughput_gain_pct / 100.0))
        recommended.append(
            Sample(labels, 1.0 if lr.layer == result.recommended_layer else 0.0)
        )

    metrics = [
        Metric(
            "pat_build_info",
            "Build information for the running pat exporter (constant 1).",
            [Sample({"version": _package_version()}, 1.0)],
        ),
        Metric(
            "pat_workload_requests_per_second",
            "Configured workload demand in requests per second.",
            [Sample({}, requests_per_second)],
        ),
        Metric(
            "pat_workload_avg_latency_ms",
            "Configured workload average latency in milliseconds.",
            [Sample({}, avg_latency_ms)],
        ),
        Metric(
            "pat_recommended_replicas",
            "Recommended replica count to saturate demand at each layer.",
            replicas,
        ),
        Metric(
            "pat_estimated_throughput_rps",
            "Estimated throughput (req/s) at the recommended replica count per layer.",
            throughput,
        ),
        Metric(
            "pat_response_time_ms",
            "Estimated response time (ms) at the recommended replica count per layer.",
            response_time,
        ),
        Metric(
            "pat_throughput_gain_ratio",
            "Throughput gain over the single-replica baseline as a ratio "
            "(0.10 == +10%).",
            gain_ratio,
        ),
        Metric(
            "pat_layer_recommended",
            "1 for the cross-layer recommended layer, 0 otherwise.",
            recommended,
        ),
    ]

    if cost_per_replica_hour is not None:
        metrics.extend(_cost_metrics(result, cost_per_replica_hour))

    metrics.extend(
        _energy_metrics(
            result, requests_per_second, avg_latency_ms, layer, replica_power_watts
        )
    )

    return metrics


def _energy_metrics(
    result: object,
    requests_per_second: float,
    avg_latency_ms: float,
    model_layer: str | None,
    replica_power_watts: float,
) -> list[Metric]:
    """MODELLED per-layer energy gauges from the analytic energy model.

    Uses :func:`energy.layer_energy` over the same analysis result, so the
    exported energy figures match what ``pat analyze`` renders. A layer whose
    model yields ``None`` (J/req or EEI undefined at zero throughput) contributes
    no sample for that gauge — an honest gap, not a fabricated 0. HELP text marks
    every gauge as modelled (E1a hygiene: these are model outputs, never signed
    measurements).
    """
    base_cap = base_capacity_rps(
        requests_per_second, avg_latency_ms, resolve_concurrency(model_layer)
    )
    jreq: list[Sample] = []
    watts: list[Sample] = []
    eei: list[Sample] = []
    for lr in result.layers:  # type: ignore[attr-defined]
        le = layer_energy(
            lr.layer,
            lr.optimal_replicas,
            requests_per_second,
            base_cap,
            replica_power_watts,
            model_layer,
        )
        labels = {"layer": lr.layer.value}
        watts.append(Sample(labels, le.watts))
        if le.joules_per_request is not None:
            jreq.append(Sample(labels, le.joules_per_request))
        if le.eei is not None:
            eei.append(Sample(labels, le.eei))
    return [
        Metric(
            "pat_energy_per_request_joules",
            "Energy per request (joules) at the recommended replica count per "
            "layer — modelled (analytic energy model).",
            jreq,
        ),
        Metric(
            "pat_power_watts",
            "Total power draw (watts) at the recommended replica count per layer "
            "— modelled (analytic energy model).",
            watts,
        ),
        Metric(
            "pat_energy_efficiency_index",
            "Energy-Efficiency Index (throughput gain vs energy-intensity change "
            "from the single-replica baseline) per layer — modelled (analytic "
            "energy model).",
            eei,
        ),
    ]


def measured_energy_metrics(db_path: object = None) -> list[Metric]:
    """The most recent MEASURED power per (layer, meter) from the energy store.

    Reads the chained ``energy_observations`` store and emits one
    ``pat_measured_power_watts`` sample per (layer, meter) at its latest reading.
    HELP marks these MEASURED — a real watt from a real meter, distinct from the
    modelled gauges — so a dashboard or alert never confuses a model output with
    a signed measurement (E1a). Returns ``[]`` when the store holds no energy
    observations, so the series appears only when a measurement backs it.
    """
    from presidio_arch_translucency.observe import (  # noqa: PLC0415
        load_verified_energy_observations,
    )

    rows = load_verified_energy_observations(db_path=db_path)
    if not rows:
        return []
    # Rows are oldest-first, so the last write for a key is its most recent.
    latest: dict[tuple[str, str], object] = {}
    for eobs in rows:
        latest[(eobs.layer, eobs.meter)] = eobs
    samples = [
        Sample({"layer": e.layer, "meter": e.meter}, e.watts)  # type: ignore[attr-defined]
        for e in latest.values()
    ]
    return [
        Metric(
            "pat_measured_power_watts",
            "Most recent measured power draw (watts) per layer and meter — "
            "measured (chained energy observation store).",
            samples,
        )
    ]


def _cost_metrics(result: object, cost_per_replica_hour: float) -> list[Metric]:
    """Per-layer cost gauges from a uniform replica cost (USD/replica/hour)."""
    from presidio_arch_translucency.cost import (  # noqa: PLC0415
        CostParams,
        cost_per_request,
        hourly_cost,
    )

    params = CostParams(
        cost_per_container_hour=cost_per_replica_hour,
        cost_per_pod_hour=cost_per_replica_hour,
        cost_per_deployment_hour=cost_per_replica_hour,
        cost_per_node_hour=cost_per_replica_hour,
    )
    cpr: list[Sample] = []
    hourly: list[Sample] = []
    for lr in result.layers:  # type: ignore[attr-defined]
        labels = {"layer": lr.layer.value}
        cpr.append(
            Sample(
                labels,
                cost_per_request(
                    lr.layer, lr.optimal_replicas, lr.estimated_throughput_rps, params
                ),
            )
        )
        hourly.append(
            Sample(labels, hourly_cost(lr.layer, lr.optimal_replicas, params))
        )
    return [
        Metric(
            "pat_cost_per_request",
            "USD per request served at the recommended replica count per layer "
            "(uniform --cost-per-replica-hour).",
            cpr,
        ),
        Metric(
            "pat_hourly_cost_usd",
            "USD per hour at the recommended replica count per layer "
            "(uniform --cost-per-replica-hour).",
            hourly,
        ),
    ]


# -- prediction metrics (from the observation store, v0.10.0 Phase 2) ----------


def _samples_metric(n: int) -> Metric:
    return Metric(
        "pat_optimize_samples",
        "Number of observations used for the latest demand prediction.",
        [Sample({}, float(n))],
    )


def prediction_metrics_from_result(result: object) -> list[Metric]:
    """
    Build the forecast metric set from an ``optimize.OptimizeResult``.

    Pure: takes an already-computed result so the CI-band branch is testable
    without fitting a model. ``result.model`` (``sma``/``arima``) labels the
    forecast; CI-bound metrics are emitted only when the result carries an
    interval (ARIMA).
    """
    model_label = {"model": result.model}  # type: ignore[attr-defined]
    layer_label = {"layer": result.layer}  # type: ignore[attr-defined]
    metrics = [
        _samples_metric(result.samples),  # type: ignore[attr-defined]
        Metric(
            "pat_observed_rps",
            "Smoothed current demand (req/s) over the observation window.",
            [Sample(layer_label, result.sma_rps)],  # type: ignore[attr-defined]
        ),
        Metric(
            "pat_observed_latency_ms",
            "Smoothed current latency (ms) over the observation window.",
            [Sample(layer_label, result.sma_latency_ms)],  # type: ignore[attr-defined]
        ),
        Metric(
            "pat_predicted_rps",
            "Forecast demand (req/s) at the optimization horizon.",
            [Sample(model_label, result.predicted_rps)],  # type: ignore[attr-defined]
        ),
        Metric(
            "pat_predicted_recommended_replicas",
            "Replicas recommended to serve the forecast demand at the observed layer.",
            [Sample(layer_label, float(result.recommended_replicas))],  # type: ignore[attr-defined]
        ),
        Metric(
            "pat_optimize_trend_ratio",
            "Demand trend across the window as a ratio (0.10 == +10%).",
            [Sample(layer_label, result.trend_pct / 100.0)],  # type: ignore[attr-defined]
        ),
        Metric(
            "pat_optimize_horizon_minutes",
            "Forecast horizon in minutes.",
            [Sample({}, result.horizon_minutes)],  # type: ignore[attr-defined]
        ),
    ]
    if result.has_interval:  # type: ignore[attr-defined]
        metrics.append(
            Metric(
                "pat_predicted_rps_lower",
                "Lower bound (95% CI) of forecast demand (req/s).",
                [Sample(model_label, result.predicted_rps_lower)],  # type: ignore[attr-defined]
            )
        )
        metrics.append(
            Metric(
                "pat_predicted_rps_upper",
                "Upper bound (95% CI) of forecast demand (req/s).",
                [Sample(model_label, result.predicted_rps_upper)],  # type: ignore[attr-defined]
            )
        )
        lower = result.recommended_replicas_lower  # type: ignore[attr-defined]
        upper = result.recommended_replicas_upper  # type: ignore[attr-defined]
        if lower is not None and upper is not None:
            metrics.append(
                Metric(
                    "pat_predicted_recommended_replicas_lower",
                    "Lower bound of recommended replicas for the forecast CI.",
                    [Sample(layer_label, float(lower))],
                )
            )
            metrics.append(
                Metric(
                    "pat_predicted_recommended_replicas_upper",
                    "Upper bound of recommended replicas for the forecast CI.",
                    [Sample(layer_label, float(upper))],
                )
            )
    return metrics


def build_prediction_metrics(
    observations: object,
    *,
    model: str = "sma",
    horizon_minutes: float = DEFAULT_HORIZON_MINUTES,
    concurrency: float | None = None,
) -> list[Metric]:
    """
    Run an optimization pass over *observations* and return forecast metrics.

    Reads nothing itself -- the caller supplies the observation window (e.g. from
    ``observe.latest_observations``). With no observations, or when optimization
    cannot run, only ``pat_optimize_samples`` is emitted so the series still
    exists (and reads 0) on an empty store. ``model`` selects ``sma`` (cheap,
    default) or ``arima`` (heavier; recomputed each scrape).
    """
    from presidio_arch_translucency.optimize import (  # noqa: PLC0415
        OptimizeError,
        optimize_arima,
        optimize_sma,
    )

    obs = list(observations)  # type: ignore[arg-type]
    if not obs:
        return [_samples_metric(0)]
    try:
        if model == "arima":
            result = optimize_arima(
                obs, horizon_minutes=horizon_minutes, concurrency=concurrency
            )
        else:
            result = optimize_sma(
                obs, horizon_minutes=horizon_minutes, concurrency=concurrency
            )
    except OptimizeError:
        return [_samples_metric(len(obs))]
    return prediction_metrics_from_result(result)


# -- HTTP serving --------------------------------------------------------------


def is_loopback_host(host: str) -> bool:
    """True when *host* is a loopback address (or the literal ``localhost``)."""
    if host == "localhost":
        return True
    try:
        return ipaddress.ip_address(host).is_loopback
    except ValueError:
        return False


def handle_request(path: str, provider: Callable[[], str]) -> tuple[int, str, bytes]:
    """
    Map a request path to ``(status, content_type, body)``.

    Pure and side-effect-free so it is testable without a socket. ``provider``
    is called only for the metrics path and returns the exposition text.
    """
    path = path.split("?", 1)[0]
    if path == METRICS_PATH:
        return 200, CONTENT_TYPE_METRICS, provider().encode("utf-8")
    if path in HEALTH_PATHS:
        return 200, CONTENT_TYPE_TEXT, b"ok\n"
    if path == "/":
        return 200, CONTENT_TYPE_TEXT, f"pat exporter -- GET {METRICS_PATH}\n".encode()
    return 404, CONTENT_TYPE_TEXT, b"not found\n"


def _make_handler(provider: Callable[[], str]) -> type[BaseHTTPRequestHandler]:
    class _MetricsHandler(BaseHTTPRequestHandler):
        # Only GET is implemented -> any other method gets 501 (read-only).
        def do_GET(self) -> None:  # noqa: N802
            status, content_type, body = handle_request(self.path, provider)
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def log_message(self, *args: object) -> None:
            # Silence the default stderr access log.
            return

    return _MetricsHandler


def build_server(host: str, port: int, provider: Callable[[], str]) -> HTTPServer:
    """Create (but do not start) the read-only metrics HTTP server."""
    return HTTPServer((host, port), _make_handler(provider))
