"""
HorizontalPodAutoscaler manifest emitter (v0.8.0, Phase 5).

Turns an optimisation recommendation into an apply-able Kubernetes HPA manifest:

    pat optimize --model arima --emit-hpa-patch --target web > hpa.yaml
    kubectl apply -f hpa.yaml

Security (v0.8.0 spec): the output is sanitised — it contains only integers
(replica counts) and Kubernetes resource names that have been validated against
the RFC 1123 label/subdomain grammar.  No secrets and no raw user input are ever
echoed, so the YAML cannot be used to smuggle arbitrary content.  The manifest is
built by hand (no PyYAML dependency); because every interpolated value is either
an ``int`` or an already-validated name, no quoting or escaping is required.
"""

from __future__ import annotations

import re

# RFC 1123 label: lowercase alphanumeric, '-' allowed internally; ≤ 63 chars.
_RFC1123_LABEL = re.compile(r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?$")
_MAX_LABEL_LEN = 63

_TARGET_API_VERSION = "apps/v1"
_TARGET_KIND = "Deployment"
_HPA_API_VERSION = "autoscaling/v2"


class HpaPatchError(ValueError):
    """Raised when a name is invalid or replica bounds are nonsensical."""


def _validate_name(value: str, field: str) -> str:
    """Validate *value* as an RFC 1123 name; raise on anything else."""
    if (
        not isinstance(value, str)
        or len(value) > _MAX_LABEL_LEN
        or not _RFC1123_LABEL.match(value)
    ):
        raise HpaPatchError(
            f"{field} {value!r} is not a valid Kubernetes name "
            "(RFC 1123: lowercase alphanumeric and '-', max 63 chars)"
        )
    return value


def build_hpa_patch(
    target: str,
    min_replicas: int,
    max_replicas: int,
    namespace: str | None = None,
    hpa_name: str | None = None,
) -> str:
    """
    Build an apply-able HorizontalPodAutoscaler manifest (YAML string).

    ``target`` is the Deployment to scale; ``hpa_name`` defaults to ``target``.
    ``min_replicas`` / ``max_replicas`` are clamped so ``max >= min >= 1``.  All
    names are RFC 1123-validated (raising :class:`HpaPatchError` otherwise).
    """
    target = _validate_name(target, "target")
    name = _validate_name(hpa_name, "hpa-name") if hpa_name else target
    namespace = _validate_name(namespace, "namespace") if namespace else None

    mn = int(min_replicas)
    if mn < 1:
        raise HpaPatchError("min_replicas must be >= 1")
    mx = max(int(max_replicas), mn)

    lines = [
        "# Generated by `pat optimize --emit-hpa-patch`. Review before applying.",
        f"apiVersion: {_HPA_API_VERSION}",
        "kind: HorizontalPodAutoscaler",
        "metadata:",
        f"  name: {name}",
    ]
    if namespace is not None:
        lines.append(f"  namespace: {namespace}")
    lines += [
        "spec:",
        "  scaleTargetRef:",
        f"    apiVersion: {_TARGET_API_VERSION}",
        f"    kind: {_TARGET_KIND}",
        f"    name: {target}",
        f"  minReplicas: {mn}",
        f"  maxReplicas: {mx}",
    ]
    return "\n".join(lines) + "\n"
