"""Tests for the Prometheus rules emitter (`pat rules`, v0.11.0)."""

import pytest
from typer.testing import CliRunner

from presidio_arch_translucency.cli import app
from presidio_arch_translucency.rules import (
    Rule,
    RuleError,
    RuleGroup,
    build_alert_group,
    build_recording_group,
    build_rule_groups,
    render_rules_yaml,
)

runner = CliRunner()


def invoke(*args: str):
    return runner.invoke(app, ["--skip-audit", *args])


def _alert_names(group: RuleGroup) -> set[str]:
    return {r.alert for r in group.rules if r.alert is not None}


# ── recording group ───────────────────────────────────────────────────────────


def test_recording_group_records() -> None:
    group = build_recording_group()
    records = {r.record for r in group.rules}
    assert {
        "pat:predicted_rps",
        "pat:observed_rps",
        "pat:demand_growth_ratio",
        "pat:trend_ratio",
    } == records


# ── alert group ───────────────────────────────────────────────────────────────


def test_alert_group_defaults_only() -> None:
    group = build_alert_group()
    assert _alert_names(group) == {
        "PatDemandSurgeForecast",
        "PatDemandTrendRising",
        "PatExporterAbsent",
    }


def test_alert_group_with_layer_adds_mismatch() -> None:
    group = build_alert_group(current_layer="container")
    assert "PatLayerTranslucencyMismatch" in _alert_names(group)
    mismatch = next(r for r in group.rules if r.alert == "PatLayerTranslucencyMismatch")
    assert 'pat_layer_recommended{layer="container"} == 0' == mismatch.expr


def test_alert_group_with_cost_adds_cost_alert() -> None:
    group = build_alert_group(cost_budget=1e-06)
    cost = next(r for r in group.rules if r.alert == "PatCostPerRequestOverBudget")
    assert "pat_cost_per_request > 1e-06" == cost.expr


def test_alert_group_surge_and_trend_thresholds_in_expr() -> None:
    group = build_alert_group(surge_ratio=1.5, trend_threshold=0.3)
    surge = next(r for r in group.rules if r.alert == "PatDemandSurgeForecast")
    trend = next(r for r in group.rules if r.alert == "PatDemandTrendRising")
    assert surge.expr == "pat:demand_growth_ratio > 1.5"
    assert trend.expr == "pat:trend_ratio > 0.3"


def test_alert_group_invalid_layer_raises() -> None:
    with pytest.raises(RuleError):
        build_alert_group(current_layer="bogus")


def test_alert_group_invalid_duration_raises() -> None:
    with pytest.raises(RuleError):
        build_alert_group(for_duration="soon")


def test_alert_group_negative_cost_budget_raises() -> None:
    with pytest.raises(RuleError):
        build_alert_group(cost_budget=-1.0)


def test_render_minimal_alert_omits_optional_blocks() -> None:
    text = render_rules_yaml(
        [RuleGroup(name="g", rules=[Rule(alert="A", expr="up == 0")])]
    )
    assert '      - alert: "A"' in text
    assert "        for:" not in text
    assert "        labels:" not in text
    assert "        annotations:" not in text


def test_exporter_absent_uses_fixed_short_for() -> None:
    absent = next(
        r for r in build_alert_group().rules if r.alert == "PatExporterAbsent"
    )
    assert absent.for_ == "5m"
    assert absent.labels["severity"] == "critical"


# ── render_rules_yaml ─────────────────────────────────────────────────────────


def test_render_quotes_and_escapes() -> None:
    group = RuleGroup(
        name="g",
        rules=[Rule(alert="A", expr='x{a="b\\c"} == 0', for_="10m")],
    )
    text = render_rules_yaml([group])
    # Inner quotes/backslashes escaped inside a double-quoted YAML scalar.
    assert r'expr: "x{a=\"b\\c\"} == 0"' in text


def test_render_full_document_shape() -> None:
    text = render_rules_yaml(build_rule_groups())
    assert text.startswith("# Generated by `pat rules`")
    assert "groups:" in text
    assert '  - name: "pat.recording"' in text
    assert '  - name: "pat.alerts"' in text
    assert '      - record: "pat:predicted_rps"' in text
    assert '      - alert: "PatExporterAbsent"' in text
    # Every expr scalar is quoted.
    for line in text.splitlines():
        if line.strip().startswith("expr:"):
            assert line.strip().removeprefix("expr:").strip().startswith('"')


# ── pat rules CLI ─────────────────────────────────────────────────────────────


def test_rules_cmd_default(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    result = invoke("rules")
    assert result.exit_code == 0, result.output
    assert "groups:" in result.output
    assert "PatDemandSurgeForecast" in result.output
    assert "PatExporterAbsent" in result.output
    assert "PatLayerTranslucencyMismatch" not in result.output
    assert "PatCostPerRequestOverBudget" not in result.output


def test_rules_cmd_with_layer(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    result = invoke("rules", "-c", "container")
    assert result.exit_code == 0, result.output
    assert "PatLayerTranslucencyMismatch" in result.output
    assert r"layer=\"container\"" in result.output


def test_rules_cmd_with_cost_budget(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    result = invoke("rules", "--cost-budget", "0.000001")
    assert result.exit_code == 0, result.output
    assert "PatCostPerRequestOverBudget" in result.output
    assert "pat_cost_per_request > 1e-06" in result.output


def test_rules_cmd_bad_duration_exits_2(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    result = invoke("rules", "--for", "soon")
    assert result.exit_code == 2
    assert "duration" in result.output.lower()


def test_rules_cmd_bad_layer_exits_2(tmp_path, monkeypatch) -> None:
    monkeypatch.setenv("HOME", str(tmp_path))
    result = invoke("rules", "-c", "bogus")
    assert result.exit_code == 2
